version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=furkan10
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_USER=springuser
      - MYSQL_DATABASE=db_example