version: "3.9"
services:
  warehousedb:
    container_name: warehousedb
    image: mysql:8
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=furkan10
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_USER=springuser
      - MYSQL_DATABASE=db_example

  warehouse:
    container_name: warehouse
    build: .
    depends_on:
      - warehousedb
    restart: on-failure
    ports:
      - 9003:9003