version: "3.9"
services:
  app:
    container_name: Warehouse
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./:/app/app